"""sync_models_with_database

Revision ID: 26999012527c
Revises: add_email_verification
Create Date: 2025-09-22 14:52:09.352516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26999012527c'
down_revision = 'add_email_verification'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.alter_column('entries', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_preferences', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               nullable=False)
    op.alter_column('user_preferences', 'preferences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user_preferences', 'preferences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               nullable=True)
    op.alter_column('user_preferences', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'USD'::character varying"),
               nullable=True)
    op.alter_column('entries', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'USD'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    # ### end Alembic commands ###