"""fix_missing_ai_columns

Revision ID: 89a4ade8868e
Revises: 20250102_0001_add_ai_features
Create Date: 2025-09-25 14:12:17.932030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '89a4ade8868e'
down_revision = '20250102_0001_add_ai_features'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_ai_preferences_id', table_name='user_ai_preferences')
    op.drop_table('user_ai_preferences')
    op.drop_index('ix_ai_models_id', table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index('ix_ai_suggestions_id', table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    op.add_column('entries', sa.Column('ai_suggested_category_id', sa.Integer(), nullable=True))
    op.add_column('entries', sa.Column('ai_confidence_score', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('entries', sa.Column('merchant_name', sa.String(length=255), nullable=True))
    op.add_column('entries', sa.Column('location_data', sa.String(), nullable=True))
    op.add_column('entries', sa.Column('ai_processed', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'entries', 'categories', ['ai_suggested_category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_column('entries', 'ai_processed')
    op.drop_column('entries', 'location_data')
    op.drop_column('entries', 'merchant_name')
    op.drop_column('entries', 'ai_confidence_score')
    op.drop_column('entries', 'ai_suggested_category_id')
    op.create_table('ai_suggestions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('suggested_category_id', sa.INTEGER(), nullable=True),
    sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), nullable=True),
    sa.Column('model_id', sa.INTEGER(), nullable=True),
    sa.Column('user_feedback', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_suggestions_id', 'ai_suggestions', ['id'], unique=False)
    op.create_table('ai_models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('model_version', sa.VARCHAR(length=20), nullable=False),
    sa.Column('model_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_models_id', 'ai_models', ['id'], unique=False)
    op.create_table('user_ai_preferences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('auto_categorization_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('prediction_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('insights_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('notification_preferences', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_user_ai_preferences_id', 'user_ai_preferences', ['id'], unique=False)
    # ### end Alembic commands ###